[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "5fce9d7192b10752c330a2bed8555c123cd44656"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "f8e7459833b05feeb696f42d5470bd930ed3bb7e5fe339beadbda880050ad57d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.x86_64-unknown-freebsd11.1.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "00fb3ece798b6cfdee566e1a1e56e6ad15fa81cd"
os = "windows"

    [[LibGit2.download]]
    sha256 = "166bad1cbe600917620cef1226921a27a2965fd81922e198512cbc987906ca16"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.x86_64-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "771bc1b596ed735eb883710196312370886d3f0f"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "191df9722b8cc895658d1fd82bb7e02630e589b60c1ac7c5747e44355cf43ca7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "armv7l"
git-tree-sha1 = "29db19c3f7e6d74c731620cfdbcf94943f99308c"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b8c08b616c549bab10188ad7a5ff24d962aa0a493692a377f4a44b19a90a17a6"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "0b2d802aecc1f22e1f63065d9f1b3032c1f5247d"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b547f9feee43987da06319a2914b6b4e301f11d53e6ed472957e23d907996cdc"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "43a9d587f4c2fd138b1f1f8d07fc7fb117fbc0fd"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "aff77d84cb8c5d61f9596ce1db8deae4065fec565a3e6344870a2773ff0b8542"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "b931988269b4a3eb622d3debb788f56b2f0b653b"
os = "windows"

    [[LibGit2.download]]
    sha256 = "aff2aa29f53a12e73fd801bdb94d37a2399cf7f1256482d8acf7c3b1a78a0364"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "fd498c05c52ffc27ed1691b8bff251107e0dab4e"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "a1a08effa7dbc8601cd300bb82e47666f6f7d23adef6ec635d830696dcb6ee14"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "8f2d1e3ea005af918d747d308fdb58864289d006"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "3fa5d44a5b4ab6ff0e0f148295753783d77c9a923e7c0be604cafb913292180b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "f73d266ea93e06fac756503c93e7bba00c6216d8"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "8d07171170223b92c2c2bb66718118aeedc9a6e354eb2b5c871b1ad1402886a9"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "6e16d9bb95d35e3ef8799c22de7c044d4b3070f7"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "aaf26cfcde46b49084e6cd0acf47c5b6699a408e80702f95cacb2bd3b23c01fc"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d6aabf7feefe60292be9a1acd36415ac7fd2014b"
os = "macos"

    [[LibGit2.download]]
    sha256 = "6d63655ca642cf72cc3c08884556be8cde820010f2ded196bc79e9a8e4562281"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.x86_64-apple-darwin14.tar.gz"
[[LibGit2]]
arch = "armv7l"
git-tree-sha1 = "9c77bd6a7c0d0dc16a1225bb8447376aa853c6de"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9dc55ff4d1c5b8772b64e5ef4a0582a3ba59795a7d8b891bfe03ba61db3dfcc2"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v0.28.5+0/LibGit2.v0.28.5.armv7l-linux-gnueabihf.tar.gz"
