[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "fdc993e24af9093069e8a923d1d27f976db2fab2"
os = "macos"

    [[LibGit2.download]]
    sha256 = "e3b108b1d23aad13ca62d519c94a6d3e451acb8ef537ed739197e065fd2c69bd"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "332e9d4d0dfbce30ae9c0e85179a5860a641605c"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "bbffb55db7b42badce4554e1bfb17cbcefdc3128998e473fdc96e1cdb73aad75"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "b9f2741de20966bfcc90f000019258136e51ffad"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9248d521b30a305aa46369341036ab031cabf9c7cf91f40d8e21fc2099a0ce75"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d816690e5efdf5a8e7ecea7a2296234973618bc"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f433260b6eb34ff1c5acf2af963e8e571d40f16de88f4244fa9cbf124ba960a9"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1a8fc67e48aeafbe3d837dcf6ee99d7cd2941f77"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5b5f2eb541880bb168298892814174be9dc1fd3861971ab8466b255926912809"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eed684e7b06677bee2b06bab7f717dd7eb04f8cf"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "ccea1d5c81197c7711e87a1b6049295b2bef6bb700598172d2c41d72da76fc71"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a58574bdeaf959f1e733b5a79c99e96c2474fb46"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6526b8bea8a03dd7f13b665b8f0680b8b600eabac7b92261a3ce7edb7ee1caa3"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "c434cc5a03901c213cd1b8f62672734d2bcd6b89"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "117ba55130283b2b020285676a4feabb63a66fa7359a17d57ca33a62171b1f76"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "f1a5e7aee43293cbf0894720b862a80393289001"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "d43c4448625e3faed9b17460f11f5419d65bb0ca6b487476244bde9d8111e64b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "d1659deac526a794b3c46d9e2dcc95780c9372ca"
os = "windows"

    [[LibGit2.download]]
    sha256 = "fea41cfdd725443444942bff63109f244377b3a6f2e1f0aa5361efdda6ba68ed"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "7de18fa2f1130acb0c2f502a21e74f81b382b0e4"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6953379cd80866fc336a95980db9380cffe0a1f6daef0ce7bc1854902d8ab60a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "bdc7dbb8642f46306961e09039886d511e8f3804"
os = "macos"

    [[LibGit2.download]]
    sha256 = "08491d53e5f4e333e7e220197f35aab192871f0aa7d7b1002a821ce3c3d8d2e1"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "13fdbf69d66389154411271ff01a22f8ff5302e8"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "0e0495caa70938428b37b86dd15d930cc85121233a9311cb33187c17b884afda"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "264aac51b199b2d8b78a384880f4c63f6b0d2b41"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "529e15a2b842948faa69a1d38e33eb52363e3d23b1450de7005cf36018bb0617"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "f86b49d73d0238077f10116458dcaf2981c78a48"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "6a43017dc0890d2e30262fd9da55097bcfcf7a6b82c9983a87150aeb9e51461f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d403914f8fd021badc9330b41102fc1c672dc774"
os = "windows"

    [[LibGit2.download]]
    sha256 = "d287a290d1fc472eeb21f8eec06a1090a2c3a723bf238f3fd1258b68fb11f8a4"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.1+0/LibGit2.v1.2.1.x86_64-w64-mingw32.tar.gz"
