[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "09fa98ba25c8ddd3a2757b71a0564deed6b4fa93"
os = "macos"

    [[LibGit2.download]]
    sha256 = "6827e6352fcb69b82e2e3ec9ee6e575c512efc66736a9a1f3ef61d3d2580c8ef"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "94273b33b7828ce6a2619cd37efd2050855c785b"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "13c81f35b4cd411232f1bd7470157fcb8e9f93192840d61682942a7fde57fad0"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "c11a935c4ffd77467b6897ac6d5832e1f8637eb2"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "21429c6deeb1665de12e9f96d0bba5afee4c8b31adcadad0fa1539040fada621"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3b7265f50b31d5079492a8a86069a9673d5e10e"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "ac5eca184111665b69ed3f8150d7fb5f9fb24dd46bce6c6985471bb832486062"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1014f858ddbb43816290928617e447cb903d515b"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "64cd0b2cd2770be6af239814e979a3fc48829af69a13e73c38b0882548a15bc3"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "90ee2ddcd6b2676b0d0d0d549155e70757c01d94"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "532603dc4affc24b7c50a152e51be39f7753637a3a0a22accac8ef8f3ad3c5b4"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7996302734a4a72825c7f988bb723c3a85207737"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "065c0eeb95141c96dc188ceaa871c1ecd7a43a52084da89c79c6870f785c65a9"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "14f356009f511c864c9c63cde2f2f7949367d61c"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "4915e4a8042d449235458087b76d74c219a4b867ab1cb0d2c96c263310a9320b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "4252a86de5e652e86c9a94390a0d587cdcc27737"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "0fe73447d5011e08b7f27cf655d9b0fe33b808a8daeb7f47e0ebb000f5aaf8f8"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "d6d15f2b2e0c18d05e20cfff17a733855213754b"
os = "windows"

    [[LibGit2.download]]
    sha256 = "67556cd1aaba838972742fdd73a58665390322b8a7cb3dc9e19fff03058fc7c2"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "2c9aaf6e685ec93ff7191ae25533f8a0d06eb8ff"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "0d861b58df6637e384297441a4264418876c945c65a74b6e5cca87b882a2e104"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "bc957a46b20d65de4e39c2caa6e19aa136406edf"
os = "macos"

    [[LibGit2.download]]
    sha256 = "7e7fb9657fb177f8892b2029d27748246ec26ec8e6589a2834ac59fdbbfd0b64"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "7969daf646b11b6fc4373b5f536a4b3f906a7ece"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "71608a20544893e9a3562796b807f96a47ac94effbbf2e3361d67c286b2ccc81"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "35b873b063583bab9230d7ee96a8cb390a1e7a0b"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibGit2.download]]
    sha256 = "028c854a42edcf012c00847c62326d95c5cc1bad70ecac65699857e355249e3a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "49d0ce99b2087537ed37d03bfb77b58007878d81"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6d8c3a75e34218da085105602bc0c4879f13d6c4b73aeb708fcc5c0744449b9a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "b6ca3f68619223724009252d850d9a48c054e930"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "9622f942cf0252630ceb083c9d93d2c1a0496587ef07e1b9903bacc8517d1a5f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "ae68720ccc1103b00b12608d054b469eb1f5e48a"
os = "windows"

    [[LibGit2.download]]
    sha256 = "49af1f718fe2fc663900a1e8591277d6338fb3eae829b9cb20c75624869dda2d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.5.0+0/LibGit2.v1.5.0.x86_64-w64-mingw32.tar.gz"
