[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "34cb6ff7b22301ae92d8f7d052b5a11aa022422a"
os = "macos"

    [[LibGit2.download]]
    sha256 = "139cd4a7180accbc45a92db9cf6d2904a981d64ae147a8aae85cf5c31c911caf"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "e58509ac93fbc07e26c6c5a9822939c97b78a8e0"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "1fd722a2cc7c17494011ce6da33044e4550f7d55a31214a883dd652f78ec5aa1"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "c7bb4852f56f584d522b1f68ba48dc668495f078"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "d9ec80bfd5433cb39bcfa15f7d10edd4bd491047ae9cff2bad2b6dd6199acfb1"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f4a76e32b4edc14d619f90ac9b7e78895c52c56"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "858bacb22bb9b1aed9cbbad48da83d0857648a5d0d9d1e1c21b009e02c0ed807"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cf5462dd11c1ba409398f0e3c0cf051983253b3b"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "af2aec9ee6f36a0afb4cced7b1292f2554b745ce7e01684805f20f06d91471c5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc99179fddd6f2dc07528be698f5ea291f862711"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b9aa658d29cb7bba9295446fde7bc4bdda592457e773f456cfcc9a698d3a8fb8"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae1921d12b73ed1db2a6a34f95fc427dd055bd28"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6b8011303fba454d30ce5b3ef3d331839d8e8b70ba37835a482a2781042d6ff1"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "d3ae842cf6d676f4f42b4a75a71ca0bc3ec71f59"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "85f1046f21a37e213d5d36114143991a3fa70ff8bb9d76977534571c78e97aae"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "4b2b93935ce631cd9e6f64662486afb41b70d5e8"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9288dbf87fd6c7775c5b6dc9b101828589a453e9ea448b3dad8f7aa53924c211"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "8c414bfc9626e8bea62a8a6704a499eaa1668a67"
os = "windows"

    [[LibGit2.download]]
    sha256 = "5dd08ff84dd1b2e72cd4b394894b46938044ebdfbbaf00db10f40d95535d0720"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "995f2c60eaf1e38c98120f4086d516c6ba89b20a"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "288ec14bb5b08509d2f7e4cf15b874a331de406202749b1292495a64650e3cc4"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "7ceea148052986d492b0600f0cff32b7f8ff4faa"
os = "macos"

    [[LibGit2.download]]
    sha256 = "ad3822c1e59486d56e4540814711e10ad5e3733d4bdf82c90fac2b83a3d1929e"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d60c1b338f978a6ffbdb77afaf8deb5f4f25819b"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "3e953f2aa1955280aef67c0deece93016186704d4968779de8a5562232ab1c85"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "ef2472955b4e920b0100403d1d426b434a42dcd8"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibGit2.download]]
    sha256 = "47e4eb1af4f119d82fb5983d74b8cb4931f06b461110e6282959cc421283bd7f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "e5aad9ed117412529f4d7798bada08359719622c"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "344c5d7be4df83a481391087273bd9723946e4cec9838f4cecce7e9a8d4dc792"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "9ebc83c677034e1804872ff38d5e14ac43f96984"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "e5ec9c7d918301db1613cd63b9ca4fc77c74e9989f7128143f0fbda2991f3bea"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "05284bd7e71741e9b4b4be148abb4030a4264700"
os = "windows"

    [[LibGit2.download]]
    sha256 = "cfdc510bdc52d4efd79f28ce50fa870640d904c6fc9c9f2bc44c8ae3f149c779"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+1/LibGit2.v1.8.0.x86_64-w64-mingw32.tar.gz"
