[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "553b7054b1c412429ed7d634973e15621e782909"
os = "macos"

    [[LibGit2.download]]
    sha256 = "bb7f2be845b3b131c98613c3875fae1f21908941b839e3d14e971a12f90e761f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "4032fcdcb8f8abf7a5a47f9eb022b6b39311b063"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "4e3ec44dd6f1e1964953dd86569fdd1be1edacbf4f47d0f3a0c31c41959dea88"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "ff22361324bf411311327fdb1960c83e6fd4b570"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6357a174b4edcadef6186847d99e81d1c5f5812914195aaa3570e596ba90a957"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bc5fa5222298e68a74af668bcdeb045fca985332"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "a853986691a30d713ed7dea8d52d4fbdb9c2c947d3c34f8502a5f00ab19da804"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b75f75c631b68c452206f4134098f7c3bff13e5"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "e2ec3b8b5739d9a4837549e2411f7a37d6d3ec321664c5d322dde4919628d401"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2b0cee2109d0f4c5e17b8433e71d9636c305126"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6454f547b03e8cbf70918f0f7fc3d2b71a1d2f052fc0262da92f50cdf4630b56"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "21f1a7f12fb4a21d7b5f4639fa1b670cd8f719bd"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "77b111abe5ba4e641ee1b5d5879b75c48415b44cddae47c1ded3850413a4d7ff"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "de76bc3b074bb54c5ec54daffe1467ecddf57064"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "ecf0341481dd4cda939c5fb8b05caf1f66868e62e413056dc46d64065858d20d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "c6278e6b878fcc7b8adb05f9f4b76eb55b4c03d3"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "beeec8370964abbe686d8b74a38a45e50842b7619f5ca8f837c5cfd9eeea0ded"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "b0edcaa6bd051dd8b60cd707bc8b812d7861d4e3"
os = "windows"

    [[LibGit2.download]]
    sha256 = "416654c209e3d5e7ed64beda81f573d36dc13938996f979b962e3e9b811ba93b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "2cc8d56df559df45c7981d25eb041e9c94be7053"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "d849c66fdfe2c4b9e28029c4f5618350c40f06e49e7c7db74b1de25a242e9506"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "612cf1171826d9cded53316964f1b74551614ff9"
os = "macos"

    [[LibGit2.download]]
    sha256 = "1840f9906ca4a34f27ab436120ccd9e4644df42fcfcab6a76243f7fb77f811e5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "19a5d0427e0ea072db489d17a80616cd38016e0d"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "827adc7a50f0b847c87364a2c65cca0ede9953d7aaf385e3a7e23f0e8149d9ea"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d0963611eaba04a6fcfe04c10059beab03e8d620"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibGit2.download]]
    sha256 = "5910116c8419ce48d73accdffa07e01627f2033dab2eeccff392e74bf35f01b6"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "15d00c7663102029fc2d269d4e946c43ff6238c5"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "752b665144ba6c5596c96836813e8cf6cfe9c8304d691bb2c1735f14bb1fbfd8"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "90c34021dd54ba68300c77dd46ee7af1da43e3f0"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "4bb275a40dc8ebb124a2de0c11aa1cc3ce5d22ede50865ff29e10a86918812a6"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "2722d193b556f57beb80b9b075be45be15e252f8"
os = "windows"

    [[LibGit2.download]]
    sha256 = "8e7ae8346f5606c9ce314cf641d500ccafbd0cc0fc35a083b09de747005ad939"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.6.1+0/LibGit2.v1.6.1.x86_64-w64-mingw32.tar.gz"
