[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "edbb3529d15ea10892bae45853bcd6a041f9574e"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "eab5649b164da23e903b16fbdc7868614b08213439bcd47c17dcbbc6d378283b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "2ab6a6036f924d2e93a53de111eb7301aa66628d"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "336f88d3a0b6bda5072933f09868d1de1a3df2b724e0c387a8f6f5bc50a904b5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv7l"
git-tree-sha1 = "cba92830f01baacf1d672aee9969a1861ef55bef"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "408f892b5ee616069a0630d084c01dcd5274b3c91b03c463e2280f796257f41a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
git-tree-sha1 = "56d84af1c9702dab4718afefc44c5ce0fca109a6"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b633468597c5a8e04c981241ab2dd92a138826170572068eae444f1cd22dc05f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "efd4b445ca1a25fabc09e76dbe59e35698776a4d"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "fae9471eda73e61301fe85c6c9da5df34d64be7980142f498ab5d75f71c213af"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "97c0ec104ee36731c458079e6ad7071f0c44b1ce"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b15a1c79c64dc63daa8a097402823fbacaee051a23ed0499cbb76929b2ee6538"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "6fe5c205d18578fcc1bce3cf2a4dd0ad155b2fd3"
os = "windows"

    [[LibGit2.download]]
    sha256 = "e305dedaf17000f61f4e1278cfd5b0a3a9bff97523905a681eba0718f5b4ab36"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "e269019de8190689713f0892335a3d853681f23e"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "84d7269944f151de98b7622fcebd2c97617b29b5cb21c2ffafe20811aeb38061"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "ebcfdbd21454cd4ec8f5a6775db4196cd93f8210"
os = "macos"

    [[LibGit2.download]]
    sha256 = "9d0486237fd142cc44e2ea6ace40fa6f0b00a85b24000b6a9578d093bf259bfa"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.x86_64-apple-darwin14.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "0dee9ceb80432bf02837c1227f2b55f45f8f67ad"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "948e10f495e6dae93c4a7823160c49a456643cf05b521582b272ac51a571affd"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "af72e9a7766133fee8bb2e746f443afba3c9be66"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9e18794c6cdd6eff664a2f5fe639605f28f65620de99f3adcff333fec7639e4f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "6a70b18a0ffe5b858667e9ac9279958d6d0c227d"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "22b9eb1f3ccad3fac170d41946116d1b6e58f76695813dd1309b6c3e1edeb10c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.x86_64-unknown-freebsd11.1.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "09496a71b808ee68374363e39a53ead13e6505bd"
os = "windows"

    [[LibGit2.download]]
    sha256 = "246e3e5ed9f63f2145e7a2c00b5ecb490d9f92cf29dc6f3dadb36196820d60a1"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.0.1+0/LibGit2.v1.0.1.x86_64-w64-mingw32.tar.gz"
