[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "833da8fc7fefe947eff49cb83dfeb855c0292cb4"
os = "macos"

    [[LibGit2.download]]
    sha256 = "3fab8ccb48f26a40db39202acaf5429bcb949d22a3d75f9df3e9fb82289c08b7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "6fc376616c501c33f013f88b90ef3981e0749e59"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f215ef44ab9d218f9dd04ded1bf5ab537b7a3036a97dfd2c2b0b2383a27a780a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "d01eeed41d00718a16db677df695885311d24343"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "e0bd7aff785c4d542c96c691459719cd1273a5a5f7e8c68cf7a9e737be590781"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "312bec6960cf25242bdc815824cac7196398ae6d"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f756e969dd5d77026d5d8e2ededfd13bf9824d0f2d2f898db478519aad2a1d65"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "619962cc5941fc0e6a07e688c13e8db72f1a0117"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "574438ec4008282e2d87a12ea22e5e2e896cea1f231b2ab7fa1113128d07044c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4810516b652dc54a434457014c2464b289866e3a"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b6543568b7ef62f0c2401bc7df1ae6f59b0fe428df960b28521d32dd5268eed5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae5dbc3d984ffce96189e1e9c1d4970e99b3fee8"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "3a0327cd65b36fa175e922eef2dbdfcaba9c6de3a2ec9fee2239d0be0021cfbe"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "c96481b6c6d3b99867f05ea1a7e4af100d3938ad"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "52dc8a7400711cf12879a46ee2f91a9d9a0b15fecd5500f60d949a04a8bbed9d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "2b723cf3b8a845440e0eb3117908e2ca4dc590b7"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f0b7b1eae1cf099692e5c1f3cc3ac4891a3b03b0807f900d5ff457a5e582d353"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "98a0631a60de5850a0b5b46368ca8fa5efa30171"
os = "windows"

    [[LibGit2.download]]
    sha256 = "c5128edf0c92987d4b840ccd52bf1897dca70bfc4a892685c01b5b2c99f296a5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "8aa9f4eb71af939ab7d7f7d4d4d75f129bd2918b"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "05c69feea39bfb3646808ed1f669e2e7933809071497650a6bca0207556fc325"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "dfc5c972ab98edd428dadfe0474237cf5ec515de"
os = "macos"

    [[LibGit2.download]]
    sha256 = "77c91cad2d40dd922273fcdcfd07998cd22f06ffb2f6521b7a611a346ca507c9"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "c62cb8c9ada3b476dcc7d807652d3bbc6d8bbd2f"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9d82bee665c5b8900ddd110b8668651b5f0dcc100a8769b01cf2aa7742bb51f0"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "23aaafc7ca8053e4a51d420a3b78e1f7977c0a5a"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibGit2.download]]
    sha256 = "c421b6bb8006becd4e5dc6bef2a82419cc772487dee94d7845ad83f448872d95"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "994280356e74a3054bfc5c91e93d140b49b65158"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "635c61b4ff9472dde51a5c04769df4601c11a4e4193af2b8802db88dd7c93779"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "c0f4b1e1a6ff12c781f4123a9818ca77d609e931"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "9ded632bc29c310633fd9b65affb1c5d5adc1663556b7c7cbbd3b545c00d8463"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "c964d45019a0ee78b2be9523b9fc6fc9f69e7097"
os = "windows"

    [[LibGit2.download]]
    sha256 = "bbf6ccc037cf48bc64bca3603a8350171b4e246386d776260e77ae973a9ae5d7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.4+0/LibGit2.v1.4.4.x86_64-w64-mingw32.tar.gz"
