[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "da768d3458e135296a79ed2e23b4391caf5226a1"
os = "macos"

    [[LibGit2.download]]
    sha256 = "e5f04bd5d817dfd2ccda5e20fbe2f7082b662db1e1c07dfb3453fa16c302160a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "6b5c089cbd9a77f6f83f108347b0d27883cd6df7"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "2603d08818b459dbb86076ddc97a8dff19588179af1562b2c220c7c0997fdc60"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "fe5e249d268f0172392b95fd5ce9bb7420847dcd"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "21e53f11b5258ab2cf3db350912643ed6b378eb97e1138c0684ced19919a194b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5fdab936f36afa4f209c22a82a1bdafd6883b768"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "2fd89624bca9795bf0e107a05f6c7ac517370507d25cdf9f8b41684f0f3483de"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6f9ddd718a74175da604fd6f4422ef02784fc4fd"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "cd6c5a2908f9942a33a064ebc9f5515d3aa0d3c4486cc2b8d45a6293e293e012"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a24aca6100dcfe7f5c5c6ab090745ae40e081f0e"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "52dc01c183a27fbd11ffe610b2d51060bd314c39582812b0a5f27f5796f80b50"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "497e5e537cc13f50fb3315c9d00a6b9bd3bfbf51"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "beb31d091b78d4e6276a24497c5a514e834211103bfe7ca6db640c0e834f9a59"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "026c29ccd2486e19ae5a13848bb0023450fb32e8"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5556df286b5fdc711055b0f6b4a5797583926538de851b9f42fd9600f4d51d59"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "48a685fe3e0badf2ded1dbed3e7fa4ea3e58e4be"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6e4a5f42ebcfb0f0161d9460144b31a37b265c10183f17df7649712e65ee4b43"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "9dfb8072ac435ada3e643b9903a6286150eab241"
os = "windows"

    [[LibGit2.download]]
    sha256 = "ee2ff76d6c309b2995ff399e1a7eef3c5945d2c391c1d1220505a9ce2bebec9f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "c3e8ccc14b7b874fca467a271a20c57708b9b557"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6d1d7750c03a780f2cd64ec3bee16ab1b63b97538ef1a86a72b867f09dc20a21"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "8111ec252f4ec8ba8945ac54b903c685eb4bdd9a"
os = "macos"

    [[LibGit2.download]]
    sha256 = "99093027cb5ff5270d8717cb95e527548a907b13f34bb20b197ecbc5ed9b74e0"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "b22ccf063a3ec0217369a893d225b7b996efb4a9"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "609c1b55b7302f2262472bdb16ce12f9440401a5100f78d3af75e616f0714c9c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "42f8e731043c7ce0d97eae515aea8429e136e6ba"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibGit2.download]]
    sha256 = "283836ed91f98ae149146a5c5f74ef865d7ff37c6d57e5a8c98394a6810bcc6e"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "84daab651bab33c1840e2d055ac19f5307c83616"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "afa61867962884e7217672f313b6662e1f249519ac775fd0f1edeb885ed16da6"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "7b695248dd8ceb34a236fde9493dc788a08d3fe1"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "89a101c55dd0e0fb22008db4763bde29747046979c327a4898cdb250e3d8ec0e"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "561a94ec7eaba538129b2e86c2ea9f20635cc8aa"
os = "windows"

    [[LibGit2.download]]
    sha256 = "309be5fd09d0128b8e15e28aa12dcc05b0d4be715b07fc760265d312da3baa33"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.8.0+0/LibGit2.v1.8.0.x86_64-w64-mingw32.tar.gz"
