[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "28a1c00f0c4411ac09c0d19accff94f700755968"
os = "macos"

    [[LibGit2.download]]
    sha256 = "043e03b4214658802b6517ac4f4fba97033ac54fc4d31cd7285f98d884d2fa71"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "09c7061637cb5b7687d0188856df40a67d293596"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "dbdd349ac852ec8a31eeaade55a24cc28a138d5b078764024d19339fffdc7dba"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "08cf07859593c75ae8e29452111b0bf8b4c0b70c"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9d6056031e30af650907ece790bba3c48d6b00c98ae156f7b2d6641c90746058"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7bac15a5a4e7f323de5cb47d67f591c8542831e3"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b90b4e95a0c8d8fd724f36073d4deea2aa2d270f7dcdd238d9fad3d5b7df2a0f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "86b584eb27ae97e61211ac6e7180de73b1259817"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "06fe5f76e4ccc52b3caf145eceb372a04c63e78cee510f1d3f607fdb609d44c2"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "829ae7a2de75a7859adac5fdd64b0e0aba926fb3"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "fe3cfbd5754e9c073bd78d618f8a74a0d49c797cf60c7007fc8eae83c727c265"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d83c307d175614076fa2d2821bfb4bcf9156fc56"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "fcbfb1a5f78003d5dc4bc001239da7ec5a0391d21302bf88aa4d570db6b87765"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "3160b470237c4b34a5c5d81f8da1da0f3239312d"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "566b7298d99c3348337d737e0252358ad214e0aaa8d2ca1b590e10e1e9c25ab9"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "e1be17935e48c61f52d677490dcf4a605368f293"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "2f28f26c580f8381fe4968735cbc99fbb03e9f54a40a5540fe0ce7f5709ec7da"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "26cee1a2226f301552e85d81417b8d9934a81c14"
os = "windows"

    [[LibGit2.download]]
    sha256 = "b4df0538527ee1399cbf0642697d1a8672626473c93c174311400be1871991ca"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "0adb027f2946b2d29273440c691283e25a2425c2"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "843e3067652c87606a8e2a24abc3a3df5162aabad77d71fef4c54fc02218f6d3"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "b3a56d773ba2606a4ca6c6f49ff538b484ffe9b9"
os = "macos"

    [[LibGit2.download]]
    sha256 = "8e045ba80197333380067e27162d57725c95bcbf8af517b797ee344ca8a0d476"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "1dda56a67b75ac7153dd7aa39f17ccd19f90b920"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "0b0c6e8781208f850c4b8b4ad06f18adb0813cc2f4041a43340a5e440dc4b1d4"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "bb1e418473db9d777b9f364521ebed08ec10d18f"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibGit2.download]]
    sha256 = "b04cfd27dccb00cf5d7cfbf5572228c268291892d285814fa2a8a236fb876d95"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "1c55f6e761fc83c738d0a6f1ab69e72244816d7b"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "534d634d84241a879efdd79a6645974581441bb627001281bd14d5ac1037441b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "bd6cb1c8a6f9d03917774ad6815134437a947e1c"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "a0b0b25cf342c6303b1a38277d375301e8da95c8c5a40eb89d84dc70c31b0f1c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "02eef7f9082433869a42692bf867bcd306b3b49f"
os = "windows"

    [[LibGit2.download]]
    sha256 = "28479114a387778c5c5fe73a56a82fb8fa9c932d62c7402d2985b07036dfab22"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.7.1+0/LibGit2.v1.7.1.x86_64-w64-mingw32.tar.gz"
