[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "3634b949596ef366acebb5882bdf8ef25e79783a"
os = "macos"

    [[LibGit2.download]]
    sha256 = "230233257e744132b2884779e05a146a74544445d4b52fd8f044a8d6f1730bd8"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "378e4bbacec334c7e2c5ff3bbbf6278bf9b869c1"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "a0149488a69efaff5e87f62f16e0ba550856f03bb1590cc2b0e639a349c27e5a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "c9e672dfdde4745dbfc96762c56c5773affd7d8c"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "50caa6786667c32c8e82ebe5d8771d5f30afdfc36382d32edf015055a59d60a3"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85ade8591f530253eff7f148ef84a9f0423d7708"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "81edcfd18805506c7948270c6166ac7fdc3f62f1f0188d4d8a5279a394b5f335"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "644fda76082a804190e05522190465e5fd7b73ef"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "59cccc83eba82f9ae68497782272f511f2381b1f201c6240014ec2ddf17453cd"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1825439fec8101a720b9d4ae4274e062ae3f2416"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "14a6f5e121553bc9e2cb788a439b31cee4018cdab7d4309c9efdcc5e3484c8d5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5af8fc703315cd25bcec09644dcf6df9d0e4c6b9"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f5d3f9dd623d5b96562e4ac34048fdb748e3f603aee81602f1419a7d74e6919c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "c4c1cacf4f31ef36260839128c688f202374681c"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "db0ffcef472652e68588f29fc60abcfb7905401aed3d137f8a36424b3b76b64d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "7a410daa4c93742283201cfdb28155a013ae5c44"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "a1e14ae73de046e504ec23092c168739c968c6b3b39c2a7e38761d968fc5cff7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "282df756efc90474de59d402fabbdf72323a0b05"
os = "windows"

    [[LibGit2.download]]
    sha256 = "6e4bf4157cb8f4a1dfe34255d78899a9fab9eb80c91ba61c918dd0c607fc8dec"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "d2393e5c417e075aa3fab5863f88462fc88feefc"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "0c086daf0982d66db703f9808c8b740d17283ed6f2456d06b0f87d1f789c7229"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "574e32dcc6391028f3be2b014a83b76d7fb7bdf7"
os = "macos"

    [[LibGit2.download]]
    sha256 = "3417e700d49f177f4fa0c508d7914cc9ab8390243311073248ca50f4ea7af826"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "1827ab2b701ea81ccdde01fcc13a1e50dad22031"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "16c32be721c5a84ffd856ace63fa40dba30ce2dfd1c62007acac2229b773b1d0"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "3b8e72127bbf4ef9e913d250ed3ee37b5426ed20"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "021acc66c5070368a4f61afcc511a5d4172cbea0776450e8d40ce0d25957e8a2"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "55b0fcecf28b7a1f22ccb708595db2e5f202d4e4"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "239c0cf538d2fe4d06f1580cf6241c97de1ad452573c33aa8520be5803738a18"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "f3fb8cd04c7a377cebfc2dcb96ed5d20096d0e5e"
os = "windows"

    [[LibGit2.download]]
    sha256 = "4b557d984e3f7a7a880f919e516e8469e1fb186a14647cdf9015a4508ffd46f6"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+0/LibGit2.v1.4.3.x86_64-w64-mingw32.tar.gz"
