[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "73ac94a5429113af8bd23351c0d44e0daf9f5b63"
os = "macos"

    [[LibGit2.download]]
    sha256 = "85271da510964c576d0e6ee943e0f464be6f122f8a5e2bf32910236022699094"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "da4cc3138298f8d1e51412814155515b9b81fe12"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "724048711825583a956c4a59f450f37624674e3eaa0a31661e046f6c53a9c760"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "c2867e3ad715b38a934c0d30f9e3483d99917c55"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "55091b040ffdfa421b10f56dd4762d53d25b5cbd00186c47227bee763e60c0ca"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a455610a5cbad7a1e334649390f914a0bbe419cc"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "416cd8db285994966685c361b948457f14a44d577e80be5c8d475071b0ed6c2e"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a440adbbec2988e18e32ecf8975ec94b30106a3e"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "1e8ef87251aedcf05130485faa1905c24d14552699ff6679ae58ab3d0bcc0365"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc330ca5150e5b85f0009dedd2259aa28b1acc33"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b0ce7b6cfd80f34f8d0c94133238be4404679fdd6f071fc4a291f6b7d1b664c8"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a08b6253bb2b07c6082ffa021b8a5220ca48b53"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "d0eceaa404b43bd1ef9395fbabc85a6c206880dc827ea2dd33d61864582fae03"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "5496c8e4d77defe304c254512e04d0c77ba511b4"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "dafec1ef854cddbfad40ed49476472d1e7c3e4460fe3506592a61277c4aa6578"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "21ed3e3ea75d92830748e39c7d84f524a37bb7d9"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "a05447eeb2594395fe715d0af40abc0c3c8ac26b72b7c5fb7d3169ce16854a0a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "436780308fc7f336ff10241d086582810ed6f5e3"
os = "windows"

    [[LibGit2.download]]
    sha256 = "e01baa1c52914e4ad4c51e46684fb930a26efddb2fb638ed2417b41748ddbbcf"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "0065c2404d79f7eec8d7ebf3682cfccdc46c6d37"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f643c79f624ac0154e6167eadead5e8dbdd651d0bccc15c5f7e71717a88e834e"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "6a6af1beb5de3096cda0772ebef12e6f2d833fa9"
os = "macos"

    [[LibGit2.download]]
    sha256 = "dcebe3f78d619241ff3851fd2649c561177bac47220403c75ee330775a3648d7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "da00fdad11c3fefc23101d2222a42ea244068f2c"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "21ff2d2ef7aa572db5e5d80c60057661b7fa24a444750dc14db01d484d49d704"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "8ffae64cc6dcf8caf9dbfe8737b9d61979da041f"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "0e4bca99e2be38cc34a1b81f5fb481485c06497bcb720aad902bbefba35f2174"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "04da9b6bf378a5f97835fb751377125283c8e559"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "fa039b2716b7fa742ac7e4ea90c7e3d9c4f4e8c31dbc2885c54115817c387ccb"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "9a108e8694b6ece7141d582f31372099e731a87b"
os = "windows"

    [[LibGit2.download]]
    sha256 = "228db40f45dfa8c57c354ecd02be5ecb32cfd2cdad51fb3e2485a6b92839d146"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.1.0+0/LibGit2.v1.1.0.x86_64-w64-mingw32.tar.gz"
