[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "427bfddf0284741cbb0b7e23d9dd4949ae9b9d60"
os = "macos"

    [[LibGit2.download]]
    sha256 = "057a5e5bf23de4bfb6e27259317ecde4743db0d0db6156b4c47559130466c25d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "9e4204a4949266a049a1dd002f1b9b2abe5748d8"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9fcc779854fda5e7379fe3b82a709a6f88e42925868e6e874845f9e59d89ffc3"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "69cb17416019b4c0a8db3e2c551015ad56995a85"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "d684181a65c1459ee8aa13ac7e53b2bd40b4d4aac6f7332cac23bcf812e3d74b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4f0e9306fa2df534a5f05f4eab16bfef3bbf3319"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "e7db0714d906062859494c86619fc306ce2e0a6a9e12547b66e6db24952ec321"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5c75ba10f43640ea13a7ae40390570c71ed934a8"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "614b6d09d3ce9813fae0c97c53c766feb99d13a3becc150df563eaf3f926db1f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4aee7f5effaf8d1a83e6ba8f6b0c2e11e10e8751"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "8535ffb09c298e06f3c3da6d417caa97e19ff060df13f59e2b5c9be88ee3106f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5694715759f27fd9ff795a9585d4762d58790003"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "75364b849b5bc1c08fa73529fef6ad9b5a26a43f6b98d79cef2b852bc76dee0c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "8f846363445b793764726aa616927980fe612b64"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "db438369ca51ba8080625fdc0363babd574394ee7b9f90177c5cac2060896c31"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "5aec54b46da2831644df4ed12d517946c6119975"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "38173ae5d794d68b8ac504afe5a0fdad203062ca3bcfff985ab6b4219f047b50"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "b0abbd6a238897ac2641fe33ee42a7b42e757648"
os = "windows"

    [[LibGit2.download]]
    sha256 = "909185e66b8ba5063b5bcbb817d32e992c8389b6740ad8b2f6c39a970d52234f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "8d13304caa2d8286937ca375a6dd91977cbe825e"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b6108c5d868d6fde7b8c05b95244db7603e48817be802f4756cd6ba9c175e2a7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "e8182bf517bbefee331f51ed7c6a8f74fbb95cf5"
os = "macos"

    [[LibGit2.download]]
    sha256 = "ccf7357674ddaec410db701d3ad5cb9026ae29a0100ff5c499e51f6764e04b2a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "ca726bc98c1fbcabd1e1b27f96eea1b7749fc3c9"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5f50b09220376f16401649cfdcac4b99b4b469957b6d305c061aa64332577737"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "f4f94e937541e6e6757d599cf5f959a0ea9d88df"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibGit2.download]]
    sha256 = "e641c45e05fe9294abac868dce9eaf9ace745d3814e8e89c9df7accbc0463797"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "25d8d74895bdefea837bba4e8b47781117aa316d"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "fa4209a78f3ec92be62afe44d4335a644ea2a63d01c2ceaef0c0faea80a9064b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "dfa843925ae321a17f4a9675f74d84601f48c4f9"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "7fc46a5bca69351212dc8018eb0b96ec6c5b142f10600c5d100e665a0f64f69f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "091cbf54f49bf987a06c00786fe6a253ea5e7d6e"
os = "windows"

    [[LibGit2.download]]
    sha256 = "5c647cdf673872edc1630479b9b77a9f5ae1f18712d36a0083bf69a3a16401d4"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+3/LibGit2.v1.4.3.x86_64-w64-mingw32.tar.gz"
