[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "e37d2b7eb22a7b053ac35ca5f8ccf4e0d8e33c96"
os = "macos"

    [[LibGit2.download]]
    sha256 = "bfa2b2cd57b27ced93b4fd31759ea8389a7a3027d270530625bb314ffb2a50bb"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "f24ba72368f3e0eb5b7ffebead0252c8a3e3f43b"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "a0de5809b90036ee3f7987703447a13427678cb7f5a6ed1633ac36b28eff26bc"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "753fdbcb2346e06bbf3e7dc364076bd73b81c872"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "65513b385227898e1f13d8a4e37a0e0cb2d309f261573b3be6aba98bce57c6ed"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a436913826fa1bdb5d538560ccc81b95e6e93a2"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "c3b0b99b774164717cd0d5e00dcf4086feb6ce97c50d53796b05a311999825b9"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "964b7307d89a44ec5b79904cd9c3de6aea0799fb"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "bec2b0d173cc982d58399238532a9b1fd53f8f76fd37d975a87a3cbfd913d5f1"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b91ae41c31a48f4575818f9078f8b07b8fade9f4"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "aca99bdb6e8bf40bb1ba5c6972ed9770600d21b9f39ffe84d850f3ae853f574f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "441f2bb50711349808dee0322136c50cb358c6bd"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "0fbfa92cd855a9c75137700bf33d2c2bd8919c191263fd7abe5aa58a132385ce"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "56548afe02771ef6dc5134978723b850d0aa805b"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "35fc3015a6aeb38c345cd4ce77225c7ec3004ae1760ccaad9a8427490b560028"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "49a9908946cf722f13e7a5580b732df7e57d06da"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "2f5d70a719f6a62d79a2a2e3eb36b8eea29b253af16ecc77b43990e08a9c15ea"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "a75e5c96156f80ecb71db347f4ce3f02c263131e"
os = "windows"

    [[LibGit2.download]]
    sha256 = "a2e31f92ae25310a8a0182007cf3971f6233e89e99bfcc05a67998b29d213a33"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "d338d83a6f68e960a08dfd96830dbd5267101740"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "843a199cbe74875152db65ecd4cc59971142df7436b5df87c429de4c6bb024fe"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "ad8bb78c09d1c6dae96938edeebf2a20227dafae"
os = "macos"

    [[LibGit2.download]]
    sha256 = "18f890859a89b9232d3b9a7c2cd7f91915c6d478d3bcd9066ee8ba4abad8e67f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "5889fd4852877ef8f4311a19396ae2ca8071a4ba"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "ec3782dd8ff44cab42bb8c454d076395cc18ed578607a6f2bb65457ce4f5a6e4"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "2703c8c387e780877adc7377bb68b2fe00aa3e8e"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f68caaac2e9019a52d08e7a1d52cc24cf10a76dad68b6fe4235eb9bfb1d45166"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "7da701c540feb358fd2956c2fd58ad741b8039b5"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "b43f543c589c6340782fc6d5334b46a5b3a7d06e31bdfc64ce975d798926765f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "918fa8179c365a6cee1f1e3fbff16386e21df4dd"
os = "windows"

    [[LibGit2.download]]
    sha256 = "0d2c5fd353d235928477eb300148628859c75d2348043a2dbf141f2a51d81ab2"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.4.3+2/LibGit2.v1.4.3.x86_64-w64-mingw32.tar.gz"
