[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "f6d2eba50a95c26fbdcd282a608e98500d310540"
os = "macos"

    [[LibGit2.download]]
    sha256 = "325b7459cc460d5d7ee9dfdd9804e68994a38108f4f7590af1118af962816c02"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "a64b7bfef55cebf996b18f03fc77257fd74d1eae"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9cb7f97252a3bd80290079ce06b70d9cdb1007d4cc958b7d8bd6373ea2375f22"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "ad9498d406665b00a97548f1ecc716e32f871964"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "1952365ddd02c8b6c58edee797eb18875597014dcef4b0e4efa9c2b8e4abd582"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "777e857fbebd16aada144073104a624336969a5c"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "ea8b7d91add5a7b067904dbcfd948891b8e278eda7eea8adf48b92c1f1dbb1cf"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "caa4abc025fe9451ed800be5f0e51a03a5768ad1"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "388348ee1c7279931a7a97accb01535d062460be060887d556fe727b546cc2dd"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4145f660e48dd03175e6a5c185bd48798116e633"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "2061f4ab9e21c28d4d3428f39f2203c62aac00c9a61f3f1f714fe48b754e1dd8"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa9b46edf6166aef0a98d9353856432783dca3df"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "64b523cca7cbb13b590972b4695f56da70c9598edaad25fa875f62ef25b2efc7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "83495cfed2a0e1605e9c98679a19355a5ba79aa8"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "db8ceee3e257a66a81c24e27bf6d385cd948c740acfc4665950e9e4ea93b3e0d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "dabe76a41cf454203ed8d6ba99063f99df8eb43c"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9ffdb59602871a4c19f03057d16df9dcbde8844cd64de4ca8c875786db8a7d2b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "85c8f3bb92208dcc85f73227efa4ee05deaea512"
os = "windows"

    [[LibGit2.download]]
    sha256 = "c28a26974c64fdb57fc62a5c02bbe1251b57147d46b6c889826ef97d4a84e2ac"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "5f4ccfc01492d9d3e4dc6ad395dd8828f795d808"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b4890f52052c2b9fb87815335c08a9a88c833ee6f77ee49fbd471917539fdf4f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d4bc2889643901e7e21394174b5ecd6e9272bd08"
os = "macos"

    [[LibGit2.download]]
    sha256 = "ef5d723b3c6ebf08263a9aba507bb6f75b9da2e073da336cfd2c8095084c314f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "8dbde92d25c0ab16df784514486f2e6c63b7e26b"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "e0577b4de160f2bd2e12a63cb3638b928bfd02d266709a855f3c0596fc5a6f04"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d6bcae2dc6ee4f78ca4bbc034f31ed8fb66e832a"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5603bcfff130a0334b7d0b9a925e390ecb6759fef298f9d81c2d7cc82085f1dd"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "1cd03e03bb57246d3fb13f3032fd7fdcd23c2db2"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "b1cee233409e2ab999a9b3ef8c9b9587e44e5f1e9aa14be00bde904c35be8c7a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "51a0e14278ee73e87fe49c47e54aac3b4ed4348c"
os = "windows"

    [[LibGit2.download]]
    sha256 = "537871806bb5d6535ed89d7b4ccecf48337dbde3bd9452f9391c6f18afbc61c7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.0+0/LibGit2.v1.2.0.x86_64-w64-mingw32.tar.gz"
