[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "840486c63e77cace75bac8f2db29bbb188277ffa"
os = "macos"

    [[LibGit2.download]]
    sha256 = "577ba9def41d1e3aafae7509f25f947c5881d8bf14766546b628f12285a5f3c7"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "fbfa79541acb78d9712bf80b8daac8bb3ae7375d"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "80cbb0f88c4c7ac5bae8262ebb0844d43e36695228eb992e530abdf8d89fe464"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "1cab1af7e8700ab1bedbee95593db36a62b03f31"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "dbc0651d9e431c0ceaf3c384b795d1ae42339e70da2cc14f8f072f1f77ff2f26"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8dff526788240457d525e3bd891700f3ecaa20f5"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "9b0bf8a804af1209b37e0abdb45440d86ed7a1587b9aa7507fb372f45b0d35cb"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c6980e8fb9bdd20163f6c9df223d05fee88866a"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "247b5c5db608b0fb3517ffa6313e245c318f89425e96f4b465816645428c999f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51be5a2195686b600212db237c9f45fb8407fac6"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "c6d08ad944c527918cb009ad17e47b57abc026ff29649082d5b0e21286f8e69c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "96b9b2761c58837029f783909e9fbb4546cc51d7"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5dc1a1445ee84551a942ecac37f21f3bd64ffb6876bccb854e68ce7c3ce29b1f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "f74a9efea17db7f3955d333f8963f33bbecb7bb2"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "cac942f019f91f7160fee92c383f9df0bd3bf04671256fd4332f406a5230422d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "f5bb4412c2aa4c0e7f73214bfa85854c9c9aa894"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f0d5566626da458496c09ed3579062de22de48d66edcb83c2313642b31dee4f5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "f7b05e8b3e818908d9f774b5a7ca12065888524e"
os = "windows"

    [[LibGit2.download]]
    sha256 = "52931b23132c0956cb6aa9a607aa1a53f077dd04f28b75e9289bf4a69869e25e"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "ecec75789dae612c662f721f5f489bac089360a8"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "e54730f8b851662e5415b6b0ba461f0a0542b32ee04c38e11fe4689483c0e668"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "576375672fc75363ba960e414411fa60044fe47e"
os = "macos"

    [[LibGit2.download]]
    sha256 = "3f5e9eaa20f763734432ab56e21e2d0420ff6e207ab3bc17640fd465f0ea3fc5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "c54fba6c4edcbc38d2f751663c0fc1ad451f81f5"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "353300bb9460b9cac88e422203d3f4edcdd3d942169d96fd0125221ed2c6ce76"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "25320a927ebeee61a6368c8e60fed97b02d931f4"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "11a4c598f70bc0b02d7f9c49bb363bebbdbfc12cee314550afde24c254f62449"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "a6e50b4396a119a893966a0fca1de77f9f852abd"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "15c8fdc916d9810af338e929be4c9800b06ad6febf95bff42136f052d8858355"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d0dc4006445bbddb088bc319137e16a1bb6ffc59"
os = "windows"

    [[LibGit2.download]]
    sha256 = "8881a8240b1ec30c9f1bed7c194b9d9f11f0c5fb011d66b27d864e7fa01cbe2b"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.2+1/LibGit2.v1.2.2.x86_64-w64-mingw32.tar.gz"
