[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "44d1f868bfadafc57fdb0968b3f9057847815d60"
os = "macos"

    [[LibGit2.download]]
    sha256 = "264fb359dbfb87c700350852258bc12734a1dfe48fc5189e56a2225e9011d287"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "715765b12e2f2dc334e2527a703a4703be9a9cfb"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "1fe9a49fffd8c4118c05999a09684ed0432d0157e2893d56a05f032e5386babe"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "103a7f36b71233f3adbb3a9cdfcc9953f23353c5"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f3c235d5e78bc9386fa57e870ae58a674cebe3d6bd627893bfbfe4458d8a57ab"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "335bc388caae1545da7e30070fb1e75a1c34c891"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f90ab019b69927411e8b26abe83f7e273edb4ec7195db286b48bdb586ad5ed36"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ad701925d5009c492651c0695673ee3f572f373c"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "49f93db00888096217848ce3f77046ba6aa35a48f3587835d371f9832081496c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4612dfff907015cafb4f39bc8e22e649612d6dcd"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "be4953645e58a5fa5af2201ea50bfe8082c794e45bb89c3d9133496ee3ba8571"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0a3bdd2b1ceb3ad2cecaaf0ef7242110df8031b"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "87dd0a99ee3a5338f56a45d85192ca8d7e3f2e8da061f6e020f532158fea3760"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "71b5669016f005aedef802d5032cecb86fe261ea"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5d9569b6794bd88d65fd13cc822c85fa58ec7dbcde4159d9dd04900fecc77031"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "9ebbdf5fb2dd5a5650a5a0b2b27834034197a60e"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b0486f5e1dfe7032ae8c580bc861352b7144dac4f890ef2c5d5b02f89825d2dd"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "f68b722ecaca23e298b9c73584663c0f7cc67dcc"
os = "windows"

    [[LibGit2.download]]
    sha256 = "0390957a756610eb422cf04f893baecf586f10abe14c7d7d3572c86e5af843ab"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "b1c134068ff4d0aa955b12a31fc1a3fb3490b7b2"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "2dc00926ab8b981aa4b1c35b56e5339de6c23b6aa18458b8fd96ce207a877a08"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d3b946e98161a9f22d97a5daca9aeaaa801a615b"
os = "macos"

    [[LibGit2.download]]
    sha256 = "77deaa6d497b18c0c51089b445ce3ad54b6b09b9362757c0470626f4a3335b58"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "e9121032d497e25cb2c648a015a659f694504037"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5ffdab33ccfd483c54cdf4ccc62d962028c0a12c71ca30643856bb9d672617bc"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "dfb195d5ec2853b64271e30bd4638b7884cf5a68"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "488cfedd54f8abf3c6839636648d2eb526cba7c41f06575cfd32402b33b273bb"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "0fa7ed2b17ae0180968f959676c8d4bdb78d3979"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "0ffdea4b50376575c92b2157ca03deb7e2245e8aae29d83a7331e5a64d02fb22"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "0db7fd4b90805f1ecaf842e033304ce9c5958514"
os = "windows"

    [[LibGit2.download]]
    sha256 = "1b1853be33e8044941a905e72c886d73dc07bab265eb7097de1a46a59e2ce2ed"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.3.0+0/LibGit2.v1.3.0.x86_64-w64-mingw32.tar.gz"
