[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "d1b4ae5874f22609aca08ca70ecc464c67946a2d"
os = "macos"

    [[LibGit2.download]]
    sha256 = "e40e2b9bfd33c00390c692f02e00d900bd5d143c5ad55a9e3416ef29e17a08bd"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "be3fa295b684c9b1b23dfaf76553c403e2445043"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "7b74c89748dade2d2587d2a08a13a867e46b83192f111d93d5d6a798dad4d576"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "ea9f9b883697d041619e2caf52fcbbfb70cc0240"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "e9232ddf72d8b89168977795e64e9837632ed8e70eca6e5ae582ea85e85a089e"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "910b04725c4193fda199a78e6a01faa028f4b71d"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "dfe5745b004efc27d89eef92ed81b10a114410dbc5ff884441ce0c52357d929f"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.aarch64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dffe9f65ba4cbfd0ac1823de06de25877e71b288"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "26fd66a6d21d0c6f0d8e43d8f6c739e17bf0f9ee193250998ea73da424a92988"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "001916c0345c5215d0b86251e5446da42610fb57"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5f05e7d58b3accafff0f1078a968be7a11e21c380c72c005d60118ef72a77cad"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ae6498d3379b3e89fdebacdc9969b68d603d10b"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "2702306bf2f85f2f583e638e30bc939b500a15afe06f2b2e3e0cf67845c9c4a6"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f7734573c52fb6e7833847cefe42594e736758e"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "02a36dd71ed848147ff643f4d70276c1383b93c3c13b62f2a84af392980daec1"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "7ff85b5df62fdc5b4d1cc1b0f24f0a3aaabf2d44"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "d0d37c0969d85cd3d774dc24ecef15ceeaf2009069387320f81ae844193e22c3"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "83fb09edfba8895b110ea3f5922a9a815cfacc08"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "56cdd1b3a4123440298d329dc53a006db36f9f50b5cdee61f4614db28ff4aee5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "a48535fc0dab276382a5eed15edc6c5dcc9aac14"
os = "windows"

    [[LibGit2.download]]
    sha256 = "edddde1b9f9f42217e06fccd59b0307bd9c6f35390ee23e825d15d18a7d4536e"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "a0d7036c14ee6b4a92db60aebccfc600526f1e12"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "de704fcd4709c0e95c72e8be0e9a87d729ffb94dea51c112e9878562f67c3069"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "riscv64"
git-tree-sha1 = "fb5cb8cd13924d636967ead71c47240733064e65"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b77053609b8712a70970a56a9450740027f942486cd348347ca4990768dd6dd1"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.riscv64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "fcc001fd24626abf45819c1996dbbdb5d418d308"
os = "macos"

    [[LibGit2.download]]
    sha256 = "58c9b0f1bfffa7741f6d728bda4fd4cf66c98c25b24c00bf9f81830cd243c971"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "673c8b86d9dd1509f7253e87d6d64c69d1253656"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "30c7280c91f037c663ff2531b9ae1fa5fc70704b33dfdfd3617dd2ee6a2246fb"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "1e810226f4e63610702d5d4a861eef24d9840d4f"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibGit2.download]]
    sha256 = "e55f1a6a724c98a4ee123591b14fe55044692aae68285536406114890638db9c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "d4ed992cd77410303a1a036b12a936b8b0ff4842"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "c35ba7babb22dbf8c3c6cdb3318ee23f2ba2dc9dc02d0c22308060c7c5a45b0d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "99821a8b09d200e7b58b60e60762eff7a0dd21bb"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "ae1a8d3ca6f6f9837ceef3901f475b1c22b6dbab06d0e55fb77a04b377f29a8a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "bfa358e4f54e94dedb8acdae5883387450fe777a"
os = "windows"

    [[LibGit2.download]]
    sha256 = "feb198e4d54b17e7f42afcab432849016ca9336864ecf45ba961dcc2aab36ea0"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.9.1+0/LibGit2.v1.9.1.x86_64-w64-mingw32.tar.gz"
