[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "ed96855ad06eeec8ed93ee5e05383fe5877a6e11"
os = "macos"

    [[LibGit2.download]]
    sha256 = "8234315f0ffd6ca28f08a713402fc2f29c0a41b9f8b6798a5a4596f854f11fa0"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.aarch64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "2a2ff6b63a3e39e3941eb43cb575c4ca32ed295e"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f3c828035dda9238355bf2a9e5b845a4c7916d6a21b6f3ae57b45f63b3d84b45"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.aarch64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "aarch64"
git-tree-sha1 = "2ea07778cc65b53333e2f2072cf34aa9bfe06a01"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "5f846c58301812514f20b681738948e11ee22a90b9a02572184933e06deb0c46"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.aarch64-linux-musl.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85fbad9e798933b2a40bfefd1af8dbfa5e58b0f5"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "b0385d4c661178a9f3e9472d1127498a7ce7e7f6f2162d704db1886e4298a845"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.armv6l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca4db72ddd7f847932ad50857bd2c66a6d4dfe45"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "7da278b7157adc24c21c90443f09706b3eb20fa7b5f81e9447261fceac555a05"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.armv6l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e94b20dbd3c764f2213e3f79adfc069db66d061"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "17481b34c357d7480bb6b1c44a80d97c8db2186f3b3f8fd145d1b15366191dd9"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.armv7l-linux-gnueabihf.tar.gz"
[[LibGit2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d719d6861ac4bcf5ef357a40dca56f7fdbd6a654"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f3ce3e4df90bb9f4165054e96683d384d38554b017f67080d566787fd0dc4731"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.armv7l-linux-musleabihf.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "2258366521c85438490e8f55692b21216f5495ea"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "67886fdb76306cf1b631b2f0592fa4a4ac7850bf79fea80491e49d48b8250bb6"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.i686-linux-gnu.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "46089c69b4a14963326ee2d425a001efe0cfc667"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "1763e04808bbc285c9f79f592c9785286aecbab21ef700cdc96f0eb2b730745c"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.i686-linux-musl.tar.gz"
[[LibGit2]]
arch = "i686"
git-tree-sha1 = "ae92f5f6a05afb8ee2de6004e947e60a9de112a2"
os = "windows"

    [[LibGit2.download]]
    sha256 = "c325e1b5fdb11095b4d3b259f76f5716da1cce3af488e0d1ebcc0085cbc37bed"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.i686-w64-mingw32.tar.gz"
[[LibGit2]]
arch = "powerpc64le"
git-tree-sha1 = "1e5d72f2f1b0d9cac42987e6ae0b55fbe8d796d8"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "6e8aca828a04415d5ffe92a5ab3ba9aee5c1ed2d8304ef644682cd87d95896d5"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.powerpc64le-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "affdffaf02f6671095cf0cc8ecd54712d61d2c8e"
os = "macos"

    [[LibGit2.download]]
    sha256 = "197fa798beb283b8302544dfedabe1a83cf004ef73b4eef2436b65a23c40945a"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.x86_64-apple-darwin.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "b48857f80ef0bdb8567952bfa4021f797f5fc68a"
libc = "glibc"
os = "linux"

    [[LibGit2.download]]
    sha256 = "f4b8752c957442f2484ef1a7b96e7c1eaf4ba2727f26a52b7fed1581106b7a33"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.x86_64-linux-gnu.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "92eff3027fec49e19ead11e32941762aef2f518a"
libc = "musl"
os = "linux"

    [[LibGit2.download]]
    sha256 = "618339eb656b99a68802e33b3bd84b672060a2fcfe95366db8b5e30d1a47e56d"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.x86_64-linux-musl.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "173909e756f9f7d5ea06f6505dd030a3b6eb51fa"
os = "freebsd"

    [[LibGit2.download]]
    sha256 = "274bea17c7134e2e994348dc2a2c2084df707682145daf4807e27bf76abde1c9"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.x86_64-unknown-freebsd.tar.gz"
[[LibGit2]]
arch = "x86_64"
git-tree-sha1 = "22d37fd42feefe5c17bfe3acbbfbb05e69fc1ebf"
os = "windows"

    [[LibGit2.download]]
    sha256 = "16ffcb0753ac480c7b2616835d39c237feae9d3370135102a9c3be3870b01649"
    url = "https://github.com/JuliaBinaryWrappers/LibGit2_jll.jl/releases/download/LibGit2-v1.2.3+1/LibGit2.v1.2.3.x86_64-w64-mingw32.tar.gz"
