# Autogenerated wrapper script for LibGit2_jll for x86_64-w64-mingw32
export libgit2

using LibSSH2_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("LibGit2")
JLLWrappers.@declare_library_product(libgit2, "libgit2.dll")
function __init__()
    JLLWrappers.@generate_init_header(LibSSH2_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libgit2,
        "bin\\libgit2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
